# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  target 'RunnerTests' do
    use_flutter!
    use_plugin_pods
    inherit! :search_paths
    # Pods for testing
  end

end
