name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      
      - run: flutter pub get

      - run: pod repo update
        working-directory: ios

      - run: flutter build ipa --no-codesign

      # Updated to v4
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          path: build/ios/ipa/*.ipa
          retention-days: 5

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/ipa/*.ipa
          tag: v1.0
          overwrite: true
          body: "CGI Maroc v1.0.1"
